package edu.epam.bookdao.entity;

 public enum Publisher {
    PENGUIN_RANDOM_HOUSE,
    HACHETTE_LIVRE,
    HARPERCOLLINS,
    MACMILLAN_PUBLISHERS,
    SIMON_AND_SCHUSTER,
    MCGRAWHILL_EDUCATION,
    HOUGHTON_MIFFLIN_HARCORUT,
    PEARSON_EDUCATION,
    SCHOLASTIC,
    CENGAGE_LEARNING
}
